server:
  port: 8081
spring:
  servlet:
    # 应用的访问路径
    context-path: /bang
  profiles:
#    active: yun
    active: loc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决swagger与高版本SpringBoot的冲突
  main:
    allow-circular-references: true #依赖循环


# minio 文件存储配置信息

  # 配置文件上传大小限制

#  thymeleaf:
#    prefix: classpath:/templates/  #prefix：指定模板所在的目录
##    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#    suffix: .html
#    encoding: UTF-8
#    #content-type: text/html
#    mode: HTML5


swagger:
  title: "帮帮接口文档"
  description: "帮帮接口文档"
  base-package: com.qjp.bang
  enabled: true
  version: 1.0.0

markerhub:
  jwt:
    secret: ef3af8bea39cb01a963160421b81850c
    expire: 604800
    header: Authorization


#zfb:
#  appId: 2021000121675534
#  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCUeeknlcorFlkJ62Pr1m+0EZ8Shw4/Wt1cvpHp53VJvRbabjrnF0Abygd7uIhSvD+9VGtEDUcoehlbhQXNf2olETFxu1hjLZwJBH45yUEWZ7Pwl2CsCIZituX4YxfZ4tg1CEO1BMeK/Vhy3//D87NPfV/a2kXjJcTXKeBZU4vELwHI9Qltr37843JZy4xbHws4BIFzyctHZiOlgUi7QKI1Q5sS41lICJJAC+Dm4ey0TIATUtJsTNUPPiG1Nb0/6toIdcPK6UMJV0XyxtL1myAdTiKPZCdXs776yA5Jpo/M2OT6Ub0WPLBCAJdPEfGmmz06NDAmL6syvtHmQ5zqQpkFAgMBAAECggEBAI+3YWObrdD/FLhxTIrfSch2tg7tA3F3toUrQXmzPOhfS1urDwDYlIlRiOTMvce3x8qviBSa9aHMbfcUT4WWK1wtxDpeKTP21e40lynAEGxrfNUI8d4TcmDiwL8oy9Fvre/HTCJPugZjK9Yl1CAMKChtJvdkB/nSeTH7qtlL8SG3FPl5snjrv3KtSbom1qyF614epuYnuMXAMP5hWL8C+PPUFoIpI4fBKm6O0MrRXebG0uLiAeD6MJQxJlevGeWJLC04wSsamQr7jwzan8gkdHIoYXjh+21jXZDoxkoVDElv/DWDsQaulS1HIBt6qiTUoVhQjjhmMY93RkbbhpPXDIECgYEAxo8YM7W4avZr7vamuvKuKXNH9lxZcei07rW6kGXgkdwDvuutuyXIhfeVfwpGAyE1XffRPjkXnOFs7kB9CtEtRMdGIVWYsx/8c5iBqW7SqcmuJHXA1ywvnGzeSrKMsf7lMyvFUB7i3e+QMGY5Y2emzy0P5hK4yy2zulQGOkd7gD0CgYEAv23ID1ofC4ItmKH7u43O0GpZDfQb6c4Jn3s0HqAhk8zCXFRov+I2B+z+0biSIJY4EqcFIpxwX+EaK36UHL4uKxfwWOorXqvZsQyq535W9rIJpSa3InUpd9lR/28m0bAST0z9wApy3/qbm/Vo2D55uU1+Ra516i7AZRPnOnG3AGkCgYEAnMzfxeYZbo6PCbTKUhPXKXCaQZkIIYYta90jKWjqgQUICDtBhOr/gZvU+O/5/fq5lC1hlgur8/2o8jUHCgXKA+iCH0zjO4Fk8TxcGJslzWMxHCXJVaLVLmhi2wZJST8LbO+B8BWT/sNyUGZJp5BxEGZ7iar7N6gtqFU2XcuZYdkCgYAjv82/yDXKAWqgeYe4c/guhd3RtEfONxMm/Gw0V/VNU8zsTzsssoMiocjIw65OdZ9NJHHaD9sQnMo1WzMv1vhqRdM11613xaIm5VW5W6fD9GXGuN80iSrQXf5pNInMWRRiSN+OkKT5XSTYUFFfKPO0fltZigYtUMPPXJMvH/NsGQKBgQC/OAsjOckZXpeTWssFWA5v4CBsXl7oleg8HFLs64GUOhVtEX0U3N8mqaLfFd3ZN/Q7iYkYHH3G4ujSPQXxFY28KABdEHDwtzr87nh1D61HfIQkvFSvTEu6Tm64pUPno0FGKZiW+OGee25NareE6ExXp8yeTTjolavSKxKX1gyksA==
#  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4K1Qo3/jbqhka78pKfwjDYj/fcMv76wWNAnNzERimREYi0Y9JidBuEIo/BLQCdk0K2p8yBtsCqHOn1EBhuIKApWnIsUA6M82B1hAAxYmj5OYp4wlMfdpMOHlowm2Xctc8P7z6Aoi2z5Mtti5luvKIw1zdo2QMsONgHUMIv72uEH9JZS+ehDXDrF9O2Um+hrijkcdW9dpVNxOd+WfitXqWU/ze6vSWpU7nNa4ii48zv8u6w7pTRA8bqNzAQbG+psKzfP8SfHS4cDE0EaGT0M4WrvdI5NWVlk3dbRIygLz2nz1o/RXclpvBLIOF7WC5qwVtNzWSkL9CkoqUeD3EDqc0wIDAQAB
#  notifyUrl: http://localhost:3326/alipay/success
#  returnUrl: http://localhost:3326/alipay/success
#  signType: RSA2
#  charset: utf-8
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do